version: "3.3"
services:
  webpage:
    build: ./webpage
    container_name: webpage
    ports:
      - "20000:8080"
    env_file: ./webpage/.env
  rest:
    build: ./rest
    container_name: rest
    ports:
      - "20001:5000"
    env_file: ./rest/.env
  redis:
    build: ./redis
    container_name: redis
    ports:
      - "20002:6379"
  mongo:
    build: ./mongo
    container_name: mongo
    ports:
      - "20003:27017"
    env_file: ./mongo/.env
    volumes:
      - mongodbdata:/data/db
volumes:
    mongodbdata: